/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.view;

import br.com.fatec.bean.MontarPc;
import br.com.fatec.bean.PlacaMae;
import br.com.fatec.bean.Processador;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class Menu extends javax.swing.JFrame {

    //variaveis de formularios
    private ViewMontarPc montarPc=null;
    private ViewPlacaMae placaMae=null;
    private ViewProcessador processador=null;
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_placa = new javax.swing.JButton();
        btn_processador = new javax.swing.JButton();
        btn_montar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_placa.setText("Cadastrar Placa Mae");
        btn_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_placaActionPerformed(evt);
            }
        });

        btn_processador.setText("Cadastrar Processador");
        btn_processador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_processadorActionPerformed(evt);
            }
        });

        btn_montar.setText("Montar PC");
        btn_montar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_montarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btn_placa)
                        .addGap(50, 50, 50)
                        .addComponent(btn_processador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btn_montar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_placa)
                    .addComponent(btn_processador))
                .addGap(18, 18, 18)
                .addComponent(btn_montar)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_placaActionPerformed
        if(placaMae == null) {
            placaMae = new ViewPlacaMae();
        }
        
        //exit o formulario
        placaMae.setVisible(true);
    }//GEN-LAST:event_btn_placaActionPerformed

    private void btn_processadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_processadorActionPerformed
        if(processador == null) {
            processador = new ViewProcessador();
        }
        
        //exit o formulario
        processador.setVisible(true);
    }//GEN-LAST:event_btn_processadorActionPerformed

    private void btn_montarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_montarActionPerformed
       if(montarPc == null) {
            montarPc = new ViewMontarPc();
        }
        
        //exit o formulario
        montarPc.setVisible(true);
    }//GEN-LAST:event_btn_montarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_montar;
    private javax.swing.JButton btn_placa;
    private javax.swing.JButton btn_processador;
    // End of variables declaration//GEN-END:variables
}
