/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.exercicio;

import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class Calculados extends javax.swing.JFrame {

    /**
     * Creates new form Calculados
     */
    public Calculados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        lblNumero2 = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        txtResultado = new javax.swing.JLabel();
        btnSoma = new javax.swing.JButton();
        btnSubtrair = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Básica");

        lblNumero1.setText("Numero 1");

        lblNumero2.setText("Número 2");

        lblResultado.setText("Resultado");

        txtResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSoma.setText("Somar");
        btnSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomaActionPerformed(evt);
            }
        });

        btnSubtrair.setText("Subtrair");
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });

        btnMultiplicar.setText("Multiplicar");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });

        btnDividir.setText("Dividir");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSoma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubtrair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDividir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiplicar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblResultado)
                            .addGap(18, 18, 18)
                            .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNumero2)
                            .addGap(18, 18, 18)
                            .addComponent(txtNumero2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNumero1)
                            .addGap(18, 18, 18)
                            .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumero2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSoma)
                    .addComponent(btnMultiplicar)
                    .addComponent(btnDividir)
                    .addComponent(btnSubtrair))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomaActionPerformed
        int n1, n2, resultado;
        
        //captura o que foi digitado
        //usar wrapper
        n1 = Integer.parseInt(txtNumero1.getText());
        n2 = Integer.parseInt(txtNumero2.getText());
        
        //calculo
        resultado = n1 + n2;
        
        //exibir na tela
        JOptionPane.showMessageDialog(rootPane, 
                                      "A soma é: " + resultado,
                                      "Mensagem ao Usuário",
                                      JOptionPane.INFORMATION_MESSAGE);
        
        //mostra dentro do LABEL
        txtResultado.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btnSomaActionPerformed

    
    
    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
         int n1, n2;
         float resultado;
        
        //captura o que foi digitado
        //usar wrapper
        n1 = Integer.parseInt(txtNumero1.getText());
        n2 = Integer.parseInt(txtNumero2.getText());
        
        //para converter para FLOAT
        //n2 = Float.parseFloat(txtNumero2.getText());
        
        try {
            //calculo
            resultado = (float)n1 / n2;
            
            //exibir na tela
            JOptionPane.showMessageDialog(rootPane, 
                                          "A divisão é: " + resultado,
                                          "Mensagem ao Usuário",
                                          JOptionPane.INFORMATION_MESSAGE);
        
            //mostra dentro do LABEL
            txtResultado.setText(String.valueOf(resultado));
        }
        catch (ArithmeticException ex) {
            JOptionPane.showMessageDialog(rootPane, 
                                      "Erro: " + ex.getMessage(),
                                      "Mensagem ao Usuário",
                                      JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
   int n1, n2;
         float resultado;
        
        //captura o que foi digitado
        //usar wrapper
        n1 = Integer.parseInt(txtNumero1.getText());
        n2 = Integer.parseInt(txtNumero2.getText());
        
        //para converter para FLOAT
        //n2 = Float.parseFloat(txtNumero2.getText());
        
        try {
            //calculo
            resultado = n1 - n2;
            
            //exibir na tela
            JOptionPane.showMessageDialog(rootPane, 
                                          "A subtração é: " + resultado,
                                          "Mensagem ao Usuário",
                                          JOptionPane.INFORMATION_MESSAGE);
        
            //mostra dentro do LABEL
            txtResultado.setText(String.valueOf(resultado));
        }
        catch (ArithmeticException ex) {
            JOptionPane.showMessageDialog(rootPane, 
                                      "Erro: " + ex.getMessage(),
                                      "Mensagem ao Usuário",
                                      JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
   int n1, n2;
         float resultado;
        
        //captura o que foi digitado
        //usar wrapper
        n1 = Integer.parseInt(txtNumero1.getText());
        n2 = Integer.parseInt(txtNumero2.getText());
        
        //para converter para FLOAT
        //n2 = Float.parseFloat(txtNumero2.getText());
        
        try {
            //calculo
            resultado = n1 * n2;
            
            //exibir na tela
            JOptionPane.showMessageDialog(rootPane, 
                                          "A multiplicação é: " + resultado,
                                          "Mensagem ao Usuário",
                                          JOptionPane.INFORMATION_MESSAGE);
        
            //mostra dentro do LABEL
            txtResultado.setText(String.valueOf(resultado));
        }
        catch (ArithmeticException ex) {
            JOptionPane.showMessageDialog(rootPane, 
                                      "Erro: " + ex.getMessage(),
                                      "Mensagem ao Usuário",
                                      JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_btnMultiplicarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSoma;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JLabel lblNumero1;
    private javax.swing.JLabel lblNumero2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
}
