/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.exemplo;

import br.com.fatec.bean.Televisor;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class ExemploComboBox extends javax.swing.JFrame {

    //variaveis auxiliares
    //cria o MODEL para a combo de televisores
    //todos os objetos deverão ser colocados aqui dentro deste objeto
    private DefaultComboBoxModel<Televisor> modelTelevisor = 
                new DefaultComboBoxModel<>();
    
    /**
     * Creates new form ExemploComboBox
     */
    public ExemploComboBox() {
        initComponents();
        
        //atribuir o MODEL criado para a COMBO
        cbTelevisores.setModel(modelTelevisor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFruta = new javax.swing.JLabel();
        txtFruta = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        cbFrutas = new javax.swing.JComboBox<>();
        btnRemover = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        chkDuplicata = new javax.swing.JCheckBox();
        lblTelevisor = new javax.swing.JLabel();
        txtTelevisor = new javax.swing.JTextField();
        btnInserir_Televisor = new javax.swing.JButton();
        cbTelevisores = new javax.swing.JComboBox<>();
        btnRemover_Televisor = new javax.swing.JButton();
        btnListar_Televisor = new javax.swing.JButton();
        chkDuplicata_Televisor = new javax.swing.JCheckBox();
        txtPreco = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFruta.setText("Fruta");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        chkDuplicata.setText("Aceitar Duplicatas");
        chkDuplicata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDuplicataActionPerformed(evt);
            }
        });

        lblTelevisor.setText("Televisor");

        btnInserir_Televisor.setText("Inserir");
        btnInserir_Televisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserir_TelevisorActionPerformed(evt);
            }
        });

        cbTelevisores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTelevisoresItemStateChanged(evt);
            }
        });

        btnRemover_Televisor.setText("Remover");
        btnRemover_Televisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemover_TelevisorActionPerformed(evt);
            }
        });

        btnListar_Televisor.setText("Listar");
        btnListar_Televisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListar_TelevisorActionPerformed(evt);
            }
        });

        chkDuplicata_Televisor.setText("Aceitar Duplicatas");
        chkDuplicata_Televisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDuplicata_TelevisorActionPerformed(evt);
            }
        });

        lblPreco.setText("Preço");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFruta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDuplicata))
                    .addComponent(txtFruta)
                    .addComponent(cbFrutas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(btnListar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelevisor)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInserir_Televisor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDuplicata_Televisor))
                            .addComponent(txtTelevisor)
                            .addComponent(cbTelevisores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRemover_Televisor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(btnListar_Televisor))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblPreco)
                        .addGap(18, 18, 18)
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFruta)
                            .addComponent(txtFruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInserir)
                            .addComponent(chkDuplicata))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbFrutas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListar)
                            .addComponent(btnRemover)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelevisor)
                            .addComponent(txtTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPreco)
                            .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInserir_Televisor)
                            .addComponent(chkDuplicata_Televisor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTelevisores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListar_Televisor)
                            .addComponent(btnRemover_Televisor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        if(chkDuplicata.isSelected()) {
            //Insere um item na combo
            cbFrutas.addItem(txtFruta.getText());
        }
        else
        {
            DefaultComboBoxModel<String> combo;
            combo = (DefaultComboBoxModel<String>) cbFrutas.getModel();
            
            //verificar se existe
            if(combo.getIndexOf(txtFruta.getText()) == -1) {
                cbFrutas.addItem(txtFruta.getText());
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, 
                                              "Fruta Já Existe na lista",
                                              "mensagem ao usuário",
                                              JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        //limpar o text
        txtFruta.setText("");
        
        //manda o cursor para o text de fruta
        txtFruta.requestFocus();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        //vamos remover um item selecionado
        
        //verificar se tem alguem selecionado
        if(cbFrutas.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(rootPane, 
                                          "Por favor selecione uma fruta",
                                          "Mansagem ao Usuário",
                                          JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
           //excluindo um item
            cbFrutas.removeItemAt(cbFrutas.getSelectedIndex());
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        String dados="";
        
        for(int i=0; i < cbFrutas.getItemCount(); i++) {
            dados += cbFrutas.getItemAt(i) + "\n";
        }
        
        JOptionPane.showMessageDialog(rootPane, 
                                          "Frutas Existentes: \n" + dados,
                                          "Mansagem ao Usuário",
                                          JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnListarActionPerformed

    private void chkDuplicataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDuplicataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDuplicataActionPerformed

    private void btnInserir_TelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserir_TelevisorActionPerformed
        Televisor tv = new Televisor();
        tv.setDescricao(txtTelevisor.getText());
        tv.setPreco(Double.parseDouble(txtPreco.getText()));//tem que converter
        
        //verifica se pode aceitar duplicatas
        if(chkDuplicata_Televisor.isSelected()){ //aceita duplicatas
            modelTelevisor.addElement(tv);
        }else { //não aceita duplicatas
            if(modelTelevisor.getIndexOf(tv) != -1){
                JOptionPane.showMessageDialog(rootPane,
                                              "Televisor Existentes",
                                         "Mensagem ao usuario",
                                         JOptionPane.INFORMATION_MESSAGE);
            }
            else{
            //adiciona o objeto para o Model
            modelTelevisor.addElement(tv);
            }
                 
        }
       
        
    }//GEN-LAST:event_btnInserir_TelevisorActionPerformed

    private void btnRemover_TelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover_TelevisorActionPerformed
        // TODO add your handling code here:
        modelTelevisor.removeElementAt(cbTelevisores.getSelectedIndex());
    }//GEN-LAST:event_btnRemover_TelevisorActionPerformed

    private void btnListar_TelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListar_TelevisorActionPerformed
        // Lista todos os itens existentes
        StringBuilder texto = new StringBuilder();
        
        for(int i=0; i < modelTelevisor.getSize(); i++) {
            texto.append(modelTelevisor.getElementAt(i).getDescricao()+ "  -  " +
                    modelTelevisor.getElementAt(i).getPreco() + "\n");
        }
        //exibindo
        JOptionPane.showMessageDialog(rootPane,
                                        "Televisores Cadastrados: \n " +
                                        texto.toString(),
                                        "Mensagem ao Usuário" ,
                                        JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnListar_TelevisorActionPerformed

    private void chkDuplicata_TelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDuplicata_TelevisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDuplicata_TelevisorActionPerformed
   /**
     * Este evento ocorre quando um item da combo é ocasionado DUAS chamadas
     * para este metodo
     * SELECTED
     * DESELECTED
     * @param args the command line arguments
     */
    private void cbTelevisoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTelevisoresItemStateChanged
        if(evt.getStateChange() == ItemEvent.DESELECTED){
            
        }
        else{
            Televisor t = new Televisor();
            //obtem o objeto que está sendo exibido
            t = (Televisor)evt.getItem();
            //move os dados do objeto selecionado para os texts
            txtTelevisor.setText(t.getDescricao());
            //tem que usar um WRAPPER
            txtPreco.setText(String.valueOf(t.getPreco()));
        }
        
    }//GEN-LAST:event_cbTelevisoresItemStateChanged

 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExemploComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExemploComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnInserir_Televisor;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnListar_Televisor;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnRemover_Televisor;
    private javax.swing.JComboBox<String> cbFrutas;
    private javax.swing.JComboBox<Televisor> cbTelevisores;
    private javax.swing.JCheckBox chkDuplicata;
    private javax.swing.JCheckBox chkDuplicata_Televisor;
    private javax.swing.JLabel lblFruta;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblTelevisor;
    private javax.swing.JTextField txtFruta;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTelevisor;
    // End of variables declaration//GEN-END:variables
}
